Player = Object:extend()

function Player:new(screen_width, screen_height)
  self.image = love.graphics.newImage("assets/sprite_player.png")
  self.x_position = screen_width * 0.2
  self.y_position = screen_height * 0.2
  self.rotation = 0
  self.scale_x = 0.25
  self.scale_y = 0.25
  self.x_origin = 175
  self.y_origin = 175
  self.speed = 300
  self.midpoint = 43.75

end

function Player:update(dt, screen_width, screen_height)
  -- -- Get movement from key presses
  -- if love.keyboard.isDown("up") then
  --   self.y_position = self.y_position - (dt * self.speed)
  -- end
  -- if love.keyboard.isDown("down") then
  --   self.y_position = self.y_position + (dt * self.speed)
  -- end
  -- if love.keyboard.isDown("left") then
  --   self.x_position = self.x_position - (dt * self.speed)
  -- end
  -- if love.keyboard.isDown("right") then
  --   self.x_position = self.x_position + (dt * self.speed)
  -- end
  if love.keyboard.isDown("right") then --press the right arrow key to push the ball to the right
    objects.boy.body:applyForce(400, 0)
  elseif love.keyboard.isDown("left") then --press the left arrow key to push the ball to the left
    objects.boy.body:applyForce(-400, 0)
  elseif love.keyboard.isDown("up") then --press the up arrow key to set the boy in the air
    objects.boy.body:setPosition(650/2, 650/2)
    objects.boy.body:setLinearVelocity(0, 0) --we must set the velocity to zero to prevent a potentially large velocity generated by the change in position
  end
  
  -- Check bounds
  local min_x = self.midpoint
  local max_x = screen_width - self.midpoint
  local min_y = self.midpoint
  local max_y = screen_height - self.midpoint
  if self.x_position > max_x then self.x_position = max_x end
  if self.x_position < min_x then self.x_position = min_x end
  if self.y_position > max_y then self.y_position = max_y end
  if self.y_position < min_y then self.y_position = min_y end

  --end
  --if self.x_position > (window_width - self_midpoint) then
  --  self.x_position = window_width - self_midpoint
  --end
end

function Player:draw()
  love.graphics.draw(self.image, self.x_position, self.y_position, self.rotation, self.scale_x, self.scale_y, self.x_origin, self.y_origin)
end

